project:
  type: website
  output-dir: _site

website:
  title: "Quarto static photo gallery demo"

  repo-url: "https://github.com/andrewheiss/quarto-static-photo-gallery"

  navbar:
    left:
      - text: "README"
        href: index.qmd
      - href: justified.qmd
        text: Justified
      - href: masonry.qmd
        text: Masonry
      - href: grid.qmd
        text: Grid

    right:
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/quarto-static-photo-gallery

format:
  html:
    theme:
      light:
        - zephyr
        - brand
      dark:
        - darkly
        - brand
    toc: false
